'use client';
import {MotionHeading} from './motion';
import Image from 'next/image';
import Link from 'next/link';
import {useRef} from 'react';
import type {Product} from '@/lib/types';
import {Icon} from './icon';
import {useShop} from './shop-provider';
import {Price} from './price';
export function Hero({products}:{products:Product[]}){const ref=useRef<HTMLElement>(null),shop=useShop();return <section className="hero" ref={ref} aria-labelledby="hero-title" onPointerMove={e=>{if(e.pointerType==='touch'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const b=e.currentTarget.getBoundingClientRect();ref.current?.style.setProperty('--mx',`${(e.clientX-b.left-b.width/2)*.015}px`);ref.current?.style.setProperty('--my',`${(e.clientY-b.top-b.height/2)*.012}px`);}} onPointerLeave={()=>{ref.current?.style.setProperty('--mx','0px');ref.current?.style.setProperty('--my','0px');}}><picture><source media="(max-width: 600px)" srcSet={`${process.env.NEXT_PUBLIC_BASE_PATH??''}/assets/jade-quarry-portrait.webp`}/><Image className="hero-landscape" src={`${process.env.NEXT_PUBLIC_BASE_PATH??''}/assets/jade-quarry-detail.webp`} alt="" fill sizes="100vw" loading="eager" fetchPriority="high"/></picture><div className="hero-shade"/><div className="hero-content"><MotionHeading as="h1" id="hero-title">НЕ ВСЁ ЦЕННОЕ<br/><em>лежит на виду.</em></MotionHeading><div className="hero-intro"><p>Среди сотен деталей —<br/>та самая. Найди свой скин.</p><Link className="button primary" href="/catalog">Исследовать коллекцию <Icon name="diagonal"/></Link></div><div className="hero-bottom"><Link href="#steam" className="hero-steam"><Icon name="steam" size={25}/><span>Пополнить Steam<small>И вернуться в игру</small></span><Icon name="diagonal"/></Link><span className="hero-scroll">ЛИСТАЙ. СМОТРИ. ВЫБИРАЙ.<span>↓</span></span></div></div><div className="hero-deck" aria-label="Скины из коллекции">{products.map((product,index)=><button key={product.id} className={`hero-find hero-find-${index+1}`} onClick={()=>shop.setPreviewProduct(product)} aria-label={`Открыть находку: ${product.name}`}><span className="find-label"><Icon name="plus" size={16}/></span><Image src={product.imageUrl} alt={product.name} width={520} height={400} priority/><span className="find-caption"><span>{product.weapon}<strong>{product.finish}</strong></span><Price minor={product.priceMinor}/></span></button>)}</div><div className="hero-fog" aria-hidden="true"/></section>;}
