'use client';
import {MotionHeading} from './motion';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {useRef,useState} from 'react';
import {Icon} from './icon';
import {useShop} from './shop-provider';
export function Header(){const shop=useShop(),path=usePathname(),[open,setOpen]=useState(false);const ref=useRef<HTMLButtonElement>(null);return <><a href="#main" className="skip-link">К содержимому</a><header className={`site-header ${path==='/'?'header-home':''}`} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);ref.current?.focus();}}}><Link href="/" className="wordmark" aria-label="Gems — главная">GEMS</Link><nav className={`main-nav ${open?'is-open':''}`} aria-label="Основная навигация">{[['/catalog','Скины'],['/#steam','Steam'],['/#arsenal','Арсенал']].map(([url,label])=><Link key={url} href={url} onClick={()=>setOpen(false)} aria-current={path===url?'page':undefined}>{label}</Link>)}</nav><div className="header-actions"><Link href="/catalog?saved=1" className="icon-button header-saved" aria-label="Избранное"><Icon name="heart"/></Link><Link href="/cart" className="cart-link" aria-label={`Корзина, товаров: ${shop.cart.length}`}><Icon name="cart"/><span>{shop.cart.length.toString().padStart(2,'0')}</span></Link>{shop.loggedIn?<Link href="/account" className="header-login">Кабинет</Link>:<button className="header-login" onClick={shop.login}><Icon name="steam" size={18}/><span>Войти</span></button>}<button ref={ref} className="icon-button mobile-toggle" aria-label={open?'Закрыть меню':'Открыть меню'} aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name={open?'close':'menu'}/></button></div></header></>;}
export function Footer(){return <footer className="site-footer"><div className="footer-invitation"><MotionHeading as="h2">Найди свой скин</MotionHeading><Link href="/catalog" className="button primary">Открыть каталог <Icon name="diagonal"/></Link></div><div className="footer-nav"><Link href="/" className="wordmark">GEMS</Link><nav aria-label="Внизу страницы"><Link href="/catalog">Каталог</Link><Link href="/#steam">Steam</Link><Link href="/account">Кабинет</Link><Link href="/#faq">Вопросы и ответы</Link></nav><a href="#main" className="back-top" aria-label="Вернуться наверх">↑</a></div><div className="footer-baseline"><span>© Gems, 2026</span><span>CS2 · STEAM</span><span>1 ₽ = 2 Gems</span></div></footer>;}
